#ifndef KEYS_H
# define KEYS_H

enum	e_keys
{
	ARROW_UP = 126,
	ARROW_DOWN = 125,
	ARROW_RIGHT = 124,
	ARROW_LEFT = 123,
	NUM_PLUS = 69,
	NUM_MINUS = 78,
	KEY_PAGE_UP = 116,
	KEY_PAGE_DOWN = 121,
	KEY_ASTERISK = 67,
	NUM_SLASH = 75,
	NUM_1 = 83,
	NUM_2 = 84,
	NUM_3 = 85,
	NUM_4 = 86,
	NUM_6 = 88,
	NUM_7 = 89,
	NUM_8 = 91,
	NUM_9 = 92,
	NUM_0 = 82,
	NUM_5 = 87
};

enum	e_action
{
	UP = ARROW_UP,
	DOWN = ARROW_DOWN,
	RIGHT = ARROW_RIGHT,
	LEFT = ARROW_LEFT,
	ZOOM = NUM_PLUS,
	REDUCE = NUM_MINUS,
	EXIT = 53,
	ISO = KEY_ASTERISK,
	PARALLELS = NUM_SLASH,
	LOWER = KEY_PAGE_DOWN,
	HIGHER = KEY_PAGE_UP,
	ROT_X1 = NUM_8,
	ROT_X2 = NUM_2,
	ROT_Y1 = NUM_4,
	ROT_Y2 = NUM_6,
	ROT_Z1 = NUM_7,
	ROT__Z1 = NUM_1,
	ROT_Z2 = NUM_9,
	ROT__Z2 = NUM_3,
	BACK_COLOR = NUM_5,
	PROJ_EPILEPTIC = NUM_0
};

#endif
